### ISSUE TITLE
Code School Proof

### ISSUE THREAD

**Issue by MasterAtNone91** [iinf362-cjv/Assignments#4]
Submit the image that proves that YOU completed the homework as described on the class website.

**Comment by ckelly721** [comment]
![devtools](https://cloud.githubusercontent.com/assets/14066485/9840052/fd4b3a7e-5a58-11e5-965c-7bd31c55d451.png)

**Comment by alexlee712** [comment]
![hw](https://cloud.githubusercontent.com/assets/11449253/9856407/7d731b20-5ae2-11e5-80fe-d5f4be08d31d.png)

**Comment by Chibuikem** [comment]
![screenshot 3](https://cloud.githubusercontent.com/assets/8951937/9859700/b5fe84b2-5af5-11e5-9c2b-1981dd341cd6.png)

**Comment by jblieden94** [comment]
![assignment 2](https://cloud.githubusercontent.com/assets/8417800/9863109/31930ae8-5b0b-11e5-94b7-730a7795f6e7.PNG)

**Comment by VeraYang** [comment]
![homework914](https://cloud.githubusercontent.com/assets/14079933/9864024/55dfdb26-5b13-11e5-99ea-798336bef034.png)

**Comment by kphil120** [comment]
![image](https://cloud.githubusercontent.com/assets/14082019/9866157/195826f8-5b2d-11e5-9fee-2af4182a85d9.png)

**Comment by mapleljn** [comment]
![screen shot](https://cloud.githubusercontent.com/assets/8211737/9881032/3af66d1e-5b9c-11e5-8923-26560459c110.png)

**Comment by CSAlexander21** [comment]
[inf362.docx](https://github.com/iinf362-cjv/Assignments/files/1997/inf362.docx)

**Comment by CSAlexander21** [comment]
![image](https://cloud.githubusercontent.com/assets/8669951/9886813/45866c2a-5bba-11e5-9904-22c711716f2b.png)

**Comment by CSAlexander21** [comment]
![image](https://cloud.githubusercontent.com/assets/8669951/9886845/687cb1da-5bba-11e5-99a4-c92c2918d76a.png)

**Comment by brianendres** [comment]
![inf362devtoolshw](https://cloud.githubusercontent.com/assets/14078303/9888596/f7aa2bae-5bc3-11e5-8fb9-e790347df035.png)

**Comment by Merln4052** [comment]
![screen shot 2015-09-15 at 21 52 12](https://cloud.githubusercontent.com/assets/14020661/9894658/2c7f6e4a-5bf4-11e5-9c69-b29fc381aeb2.png)
![screen shot 2015-09-15 at 21 51 16](https://cloud.githubusercontent.com/assets/14020661/9894659/2ec9d74e-5bf4-11e5-800f-afc67e5001cb.png)

**Comment by nmartucci** [comment]
![cappin](https://cloud.githubusercontent.com/assets/14042841/9920211/356f1774-5ca0-11e5-8c42-4a6a43c04abf.PNG)

To be honest the video helped but it actually confused me more than helped. Would we be able to go over this in class?

**Comment by cjs166** [comment]
![screen shot 2015-09-16 at 6 34 30 pm](https://cloud.githubusercontent.com/assets/14082031/9920382/b0883c32-5ca1-11e5-80b8-446fab6c9f1f.png)

**Comment by MasterAtNone91** [comment]
We will go over it in class tomorrow.

Chris V.


Sent from my T-Mobile 4G LTE Device


-------- Original message --------
From: nmartucci
Date:09/16/2015 6:25 PM (GMT-05:00)
To: iinf362-cjv/Assignments
Cc: "Velez, Christopher J"
Subject: Re: [Assignments] Code School Proof (#4)


[cappin]<https://cloud.githubusercontent.com/assets/14042841/9920211/356f1774-5ca0-11e5-8c42-4a6a43c04abf.PNG>

To be honest the video helped but it actually confused me more than helped. Would we be able to go over this in class?

-

**Comment by ellaorzhu** [comment]
![2015-09-16_1940](https://cloud.githubusercontent.com/assets/14044879/9921293/0e218576-5caa-11e5-8368-ed90ee3495a5.png)

**Comment by gregbedik** [comment]
![iinf 362](https://cloud.githubusercontent.com/assets/14021347/9923484/5aa2b35c-5cc3-11e5-9f76-ddeeddef4def.png)

**Comment by tlinker17** [comment]
![image](https://cloud.githubusercontent.com/assets/14044894/9924037/82c80f84-5cc9-11e5-8a39-a9f7e8c9d586.png)

**Comment by jwoa** [comment]
![screen shot 2015-09-17 at 12 59 54 am](https://cloud.githubusercontent.com/assets/14006716/9925285/832b5694-5cd7-11e5-91ae-21995df9f333.png)

**Comment by aburke2** [comment]
![alexis burke](https://cloud.githubusercontent.com/assets/14008643/9940040/4f4b4942-5d3b-11e5-9438-756086c32c41.png)

**Comment by NickEngert** [comment]
![chapter 1-3 done](https://cloud.githubusercontent.com/assets/14077257/9941637/a1ff4e3c-5d44-11e5-905e-d995e68d7923.png)

**Comment by 9one9** [comment]
![screen shot 2015-09-17 at 2 25 24 pm](https://cloud.githubusercontent.com/assets/14048478/9942313/578a06ae-5d48-11e5-8f72-b0afa60c9e8b.png)

**Comment by waveywednesday** [comment]
<img width="1276" alt="screen shot 2015-09-17 at 2 34 23 pm" src="https://cloud.githubusercontent.com/assets/14058198/9942501/57bf8760-5d49-11e5-8d7e-21c6757c6de0.png">

**Comment by sguthrie113** [comment]
![screen shot 2015-09-17 at 3 22 35 pm](https://cloud.githubusercontent.com/assets/14062023/9943544/01fe415c-5d50-11e5-9cba-80c4f984226d.png)

**Comment by LorennaFrancelino** [comment]
![homework](https://cloud.githubusercontent.com/assets/5316709/9943562/153e5f5e-5d50-11e5-95a3-6f9cba00bbda.png)

**Comment by shaniceD** [comment]
![screen shot 2015-09-17 at 3 40 47 pm](https://cloud.githubusercontent.com/assets/13009714/9944287/3ca3820a-5d54-11e5-81b9-8bda6293ccc1.jpg)

**Comment by duffmang** [comment]
<img width="1183" alt="screen shot 2015-09-17 at 3 58 03 pm" src="https://cloud.githubusercontent.com/assets/11167704/9944427/44f970da-5d55-11e5-8edc-20f780d3502a.png">

**Comment by AmandaTReis** [comment]
![hw](https://cloud.githubusercontent.com/assets/14116226/9944603/6498a7d4-5d56-11e5-89de-b42f3d1f2969.jpg)

**Comment by AmandaTReis** [comment]
the first 3 chapters of Discovering DevTools on CodeSchool.com

**Comment by MJAmk** [comment]
<img width="1440" alt="screen shot 2015-09-17 at 4 47 35 pm" src="https://cloud.githubusercontent.com/assets/8669953/9945551/f1d937e4-5d5b-11e5-97d4-b64c78c6891a.png">

**Comment by sadex3** [comment]
<img width="1253" alt="screen shot 2015-09-18 at 7 53 46 pm" src="https://cloud.githubusercontent.com/assets/7755246/9973332/0e760402-5e3f-11e5-854c-081715847f2f.png">

**Comment by kevingsp** [comment]
![image](https://cloud.githubusercontent.com/assets/8616391/9977855/18fa165c-5ee4-11e5-8ac7-090ad38fc847.png)

**Comment by kevingsp** [comment]
![image](https://cloud.githubusercontent.com/assets/8616391/9977857/25045e76-5ee4-11e5-8cb7-d19e3e26a84d.png)

**Comment by japodolla** [comment]
![screen shot 2015-09-22 at 12 05 33 am](https://cloud.githubusercontent.com/assets/10900855/10010754/d54f6372-60bd-11e5-973d-585b45a19558.png)

**Comment by Guzma13** [comment]
![latehomework](https://cloud.githubusercontent.com/assets/14080645/10023824/f8f8d84e-6121-11e5-929d-51b271a630ef.jpg)

**Comment by plarson15** [comment]
![image](https://cloud.githubusercontent.com/assets/14103012/10036079/e9048a5c-616f-11e5-8934-ae02c3d5710b.png)

**Comment by shaniceD** [comment]
![screen shot codeschool](https://cloud.githubusercontent.com/assets/13009714/11825600/f71dbf94-a34d-11e5-824d-ea1bdb48bd0b.png)
